import second from "../../../assets/Real estate/second.png";
// Listing Data
const listingData = [
    {
      img: second,
      title: "House for sale",
      location: "Itahari, Sunsari",
      date: "2081/05/06",
      price: "Rs. 8,00,000",
      land: "5 kattha",
      bed: "2 Bed",
      car: "2 Car parking",
    },
    {
      img: second,
      title: "House for sale",
      location: "Itahari, Sunsari",
      date: "2081/05/06",
      price: "Rs. 12,00,000",
      land: "5 kattha",
      bed: "2 Bed",
      car: "2 Car parking",
    },
    {
      img: second,
      title: "House for sale",
      location: "Itahari, Sunsari",
      date: "2081/05/06",
      price: "Rs. 10,00,000",
      land: "5 kattha",
      bed: "2 Bed",
      car: "2 Car parking",
    },
    {
      img: second,
      title: "House for sale",
      location: "Itahari, Sunsari",
      date: "2081/05/06",
      price: "Rs. 9,00,000",
      land: "5 kattha",
      bed: "2 Bed",
      car: "2 Car parking",
    },
    {
      img: second,
      title: "House for sale",
      location: "Itahari, Sunsari",
      date: "2081/05/06",
      price: "Rs. 7,00,000",
      land: "5 kattha",
      bed: "2 Bed",
      car: "2 Car parking",
    },
    {
      img: second,
      title: "House for sale",
      location: "Itahari, Sunsari",
      date: "2081/05/06",
      price: "Rs. 11,00,000",
      land: "5 kattha",
      bed: "2 Bed",
      car: "2 Car parking",
    },
    {
      img: second,
      title: "House for sale",
      location: "Itahari, Sunsari",
      date: "2081/05/06",
      price: "Rs. 13,00,000",
      land: "5 kattha",
      bed: "2 Bed",
      car: "2 Car parking",
    },
  ];
  export default listingData