import first from "../../../assets/Real estate/first.png";
const listingData = [
  {
    id: 1,
    img: first,
    title: "House for sale",
    location: "Itahari, Sunsari",
    date: "2081/05/06",
    price: "Rs. 8,59,000",
    land: "5 kattha",
    bed: "2 ",
    car: "2 ",
    price_text:"Eight Lakh Fifty Nine Thousand ",
    kitchen:"1",
    livingroom:"1 ",
    bathroom:"5",
    direction:"East",
    poojaroom:"1 ",
    facility:"Earthquake Resistant, Electricity, Water Supply, Telephone, Internet, Cable TV, Parking",
    desc:"Looking for a beautiful and modern home in a prime Location? This 2-Bedroom house for sale in Itahari, Sunsari offers the perfect blend of comfort, convenience, and luxury. Located near Medicity, this home is ideal for families who desire a peaceful and well-connected neighborhood.",
    contact:"9801169920, 9801169918",
  },
  {
    id: 2,
    img: first,
    title: "House for sale",
    location: "Itahari, Sunsari",
    date: "2081/05/06",
    price: "Rs. 12,00,000",
    land: "5 kattha",
    bed: "2 ",
    car: "2 ",
    price_text:"8 Lakhs",
    kitchen:"1",
    livingroom:"1 ",
    bathroom:"5",
    direction:"East",
    poojaroom:"1 ",
    facility:"Earthquake Resistant, Electricity, Water Supply, Telephone, Internet, Cable TV, Parking",
    desc:"Looking for a beautiful and modern home in a prime Location? This 2-Bedroom house for sale in Itahari, Sunsari offers the perfect blend of comfort, convenience, and luxury. Located near Medicity, this home is ideal for families who desire a peaceful and well-connected neighborhood.",
    contact:"9801169920, 9801169918",
    
  },
  {
    id: 3,
    img: first,
    title: "House for sale",
    location: "Itahari, Sunsari",
    date: "2081/05/06",
    price: "Rs. 10,00,000",
    land: "5 kattha",
    bed: "2 ",
    car: "2 ",
    price_text:"8 Lakhs",
    kitchen:"1",
    livingroom:"1 ",
    bathroom:"5",
    direction:"East",
    poojaroom:"1 ",
    facility:"Earthquake Resistant, Electricity, Water Supply, Telephone, Internet, Cable TV, Parking",
    desc:"Looking for a beautiful and modern home in a prime Location? This 2-Bedroom house for sale in Itahari, Sunsari offers the perfect blend of comfort, convenience, and luxury. Located near Medicity, this home is ideal for families who desire a peaceful and well-connected neighborhood.",
    contact:"9801169920, 9801169918",
  },
  {
    id: 4,
    img: first,
    title: "House for sale",
    location: "Itahari, Sunsari",
    date: "2081/05/06",
    price: "Rs. 9,00,000",
    land: "5 kattha",
    bed: "2 ",
    car: "2 ",
    price_text:"8 Lakhs",
    kitchen:"1",
    livingroom:"1 ",
    bathroom:"5",
    direction:"East",
    poojaroom:"1 ",
    facility:"Earthquake Resistant, Electricity, Water Supply, Telephone, Internet, Cable TV, Parking",
    desc:"Looking for a beautiful and modern home in a prime Location? This 2-Bedroom house for sale in Itahari, Sunsari offers the perfect blend of comfort, convenience, and luxury. Located near Medicity, this home is ideal for families who desire a peaceful and well-connected neighborhood.",
    contact:"9801169920, 9801169918",
  },
  {
    id: 5,
    img: first,
    title: "House for sale",
    location: "Itahari, Sunsari",
    date: "2081/05/06",
    price: "Rs. 7,00,000",
    land: "5 kattha",
    bed: "2 ",
    car: "2 ",
    price_text:"8 Lakhs",
    kitchen:"1",
    livingroom:"1 ",
    bathroom:"5",
    direction:"East",
    poojaroom:"1 ",
    facility:"Earthquake Resistant, Electricity, Water Supply, Telephone, Internet, Cable TV, Parking",
    desc:"Looking for a beautiful and modern home in a prime Location? This 2-Bedroom house for sale in Itahari, Sunsari offers the perfect blend of comfort, convenience, and luxury. Located near Medicity, this home is ideal for families who desire a peaceful and well-connected neighborhood.",
    contact:"9801169920, 9801169918",
  },
  {
    id: 6,
    img: first,
    title: "House for sale",
    location: "Itahari, Sunsari",
    date: "2081/05/06",
    price: "Rs. 11,00,000",
    land: "5 kattha",
    bed: "2 ",
    car: "2 ",
    price_text:"8 Lakhs",
    kitchen:"1",
    livingroom:"1 ",
    bathroom:"5",
    direction:"East",
    poojaroom:"1 ",
    facility:"Earthquake Resistant, Electricity, Water Supply, Telephone, Internet, Cable TV, Parking",
    desc:"Looking for a beautiful and modern home in a prime Location? This 2-Bedroom house for sale in Itahari, Sunsari offers the perfect blend of comfort, convenience, and luxury. Located near Medicity, this home is ideal for families who desire a peaceful and well-connected neighborhood.",
    contact:"9801169920, 9801169918",
  },
  {
    id: 7,
    img: first,
    title: "House for sale",
    location: "Itahari, Sunsari",
    date: "2081/05/06",
    price: "Rs. 13,00,000",
    land: "5 kattha",
    bed: "2 ",
    car: "2 ",
    price_text:"8 Lakhs",
    kitchen:"1",
    livingroom:"1 ",
    bathroom:"5",
    direction:"East",
    poojaroom:"1 "
  },
];
export default listingData;
