# Generated by Django 5.1.6 on 2025-02-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="is_feateured",
            new_name="is_featured",
        ),
    ]
