# Generated by Django 5.1.6 on 2025-02-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_is_feateured_listing_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="sq_feet",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
