# Generated by Django 5.1.6 on 2025-02-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_property_sq_feet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_buyer",
        ),
    ]
