# Generated by Django 5.1.6 on 2025-02-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_user_is_buyer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="owner",
            new_name="agent",
        ),
    ]
